// Run with NODE_PATH pointing to an installation of Playwright.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({channel: 'msedge', headless: true});
  const page = await browser.newPage({viewport: {width: 1440, height: 1080}});
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.PROGRAMMER_URL);
  await page.locator('#THROTTLE_LOW').waitFor();
  await page.getByLabel('Throttle starts at (ADC counts) in volts', {exact: true}).fill('1.5');
  assert.equal(await page.locator('#THROTTLE_LOW').inputValue(), '1229');
  await page.locator('#THROTTLE_LOW').fill('4094');
  await page.getByRole('button', {name: 'Build UF2 only', exact: true}).click();
  await page.getByText('Throttle start must be below full throttle.', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Defaults', exact: true}).click();
  await page.getByRole('button', {name: 'Hall calibration', exact: true}).click();
  await page.locator('#IDENTIFY_HALLS_ON_BOOT').selectOption('false');
  await page.getByRole('button', {name: 'Build UF2 only', exact: true}).click();
  await page.getByText('Manual hall table must contain each motor state 0–5 exactly once.', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Manual hall table', exact: true}).click();
  assert.equal(await page.locator('.hall-grid select').count(), 8);
  await page.getByRole('button', {name: 'Defaults', exact: true}).click();
  await page.getByRole('button', {name: 'Throttle', exact: true}).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', {name: 'Save profile', exact: true}).click();
  const download = await downloadPromise;
  const profile = path.resolve('.programmer/test-profile.json'); await download.saveAs(profile);
  await page.locator('#THROTTLE_LOW').fill('800');
  await page.locator('#file').setInputFiles(profile);
  await page.getByText('Profile imported into editor.', {exact: true}).waitFor();
  assert.equal(await page.locator('#THROTTLE_LOW').inputValue(), '1024');
  await page.getByRole('button', {name: 'Build UF2 only', exact: true}).click();
  await page.locator('#job-state').filter({hasText: /^(Build ready|Cached build ready)$/}).waitFor({timeout: 180000});
  await page.locator('#download').waitFor({state: 'visible'});
  await page.screenshot({path: '.programmer/preview.png', fullPage: true});
  await page.setViewportSize({width: 390, height: 844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({path: '.programmer/preview-mobile.png', fullPage: true});
  assert.deepEqual(errors, []);
  console.log('Browser passed: voltage editing, validation, manual-table controls, profile export/import, actual UF2 build, mobile layout, no JavaScript errors.');
  await browser.close();
})().catch(e => {console.error(e); process.exit(1);});
